import { Toaster } from "@/components/ui/sonner";
import QueryProvider from "@/utils/QueryProvider";
import { ReduxProvider } from "@/utils/ReduxProvider";
import { ThemeProvider } from "@/utils/ThemeProvider";
import type { Metadata } from "next";
import { Rethink_Sans } from "next/font/google";
import "./globals.css";

const rethink = Rethink_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <ReduxProvider>
        <html lang="en" suppressHydrationWarning>
          <body
            className={`${rethink.className} max-w-[1300px] antialiased`}
            suppressHydrationWarning
          >
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </body>
        </html>
        <Toaster visibleToasts={1} richColors={true} position="top-right" />
      </ReduxProvider>
    </QueryProvider>
  );
}
